"""Scaffold a paper-library-backed paper navigation site.

This module deliberately generates a small Next.js app skeleton rather than a
one-off pile of components. PaperScope owns the scholarly paper-reader surface;
LocalEvidence can call the same generator in medical mode and layer clinical
navigation around it.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from pathlib import Path
import json
import re
from typing import Literal


Mode = Literal["academic", "medical"]


@dataclass(frozen=True)
class PaperSiteConfig:
    """Configuration written into a generated paper-site scaffold."""

    project_name: str
    title: str
    mode: Mode = "academic"
    paperlibrary_root: str = "../paper-library"
    manuscript_path: str = "src/content/manuscript.md"
    references_path: str = "src/content/references.json"
    require_auth: bool = True


def scaffold_paper_site(config: PaperSiteConfig, out_dir: Path, *, force: bool = False) -> list[Path]:
    """Create a Next.js paper-reader scaffold and return written files.

    The scaffold is intentionally data-first. Generated callers replace
    ``src/content/manuscript.md`` and ``src/content/references.json`` with their
    project export, while the reader UI and CSS stay consistent across projects.
    """

    out_dir = out_dir.resolve()
    if out_dir.exists() and any(out_dir.iterdir()) and not force:
        raise FileExistsError(f"{out_dir} is not empty; pass force=True to overwrite scaffold files")

    files = {
        "README.md": _readme(config),
        "package.json": _package_json(config),
        "next.config.ts": "const nextConfig = {};\n\nexport default nextConfig;\n",
        "next-env.d.ts": '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is generated by PaperScope and maintained by Next.js.\n',
        "tsconfig.json": _tsconfig_json(),
        "src/app/layout.tsx": _layout_tsx(config),
        "src/app/page.tsx": _page_tsx(),
        "src/app/PaperReader.tsx": _paper_reader_tsx(),
        "src/app/globals.css": SHARED_CSS,
        "src/content/manuscript.md": _sample_manuscript(config),
        "src/content/references.json": _sample_references(),
        "src/content/details.json": _sample_details(),
        "paper-site.config.json": json.dumps(asdict(config), indent=2) + "\n",
    }

    written: list[Path] = []
    for relative, content in files.items():
        target = out_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.exists() and not force:
            raise FileExistsError(f"{target} exists; pass force=True to overwrite")
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "paper-site"


def _readme(config: PaperSiteConfig) -> str:
    label = "PaperScope" if config.mode == "academic" else "LocalEvidence"
    return f"""# {config.title}

Generated {label} paper-navigation site scaffold.

Shared contract:
- MD3/light-dark token palette: the shared MD3 visual contract used across the author's paper sites.
- Native web manuscript as the reading surface; PDFs are downloads only.
- Inline citation controls open the side panel first, with explicit external links inside the panel.
- More-detail markers are inline annotations, not callout blocks.
- Reference records carry paper-library status from `{config.paperlibrary_root}`
  (a permanent library at ~/paper-library by convention).
- Reference records should include reader-facing use notes when available:
  `role`, `what`, `why`, `caution`, and deduped `contexts`.
- Reference records can include `native_href` and `source_href`; citation clicks
  still open the sidebar first, and those external/native links live inside it.

Replace:
- `{config.manuscript_path}` with the rendered manuscript markdown.
- `{config.references_path}` with paper-library-backed citation records.

Optional:
- Add `src/content/sections.json` when a project needs subtabs. Each record
  can point to `manuscriptPath`/`manuscript_path` or carry inline `manuscript`.
  First visits open at the top; returning to a subtab restores its scroll.

Run:

```bash
npm install
npm run dev
```
"""


def _package_json(config: PaperSiteConfig) -> str:
    package = {
        "name": slugify(config.project_name),
        "version": "0.1.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "typecheck": "tsc --noEmit",
        },
        "dependencies": {
            "next": "latest",
            "react": "latest",
            "react-dom": "latest",
            "react-markdown": "latest",
            "remark-gfm": "latest",
            "geist": "latest",
        },
        "devDependencies": {
            "@types/node": "latest",
            "@types/react": "latest",
            "@types/react-dom": "latest",
            "typescript": "latest",
        },
    }
    return json.dumps(package, indent=2) + "\n"


def _tsconfig_json() -> str:
    config = {
        "compilerOptions": {
            "target": "ES2017",
            "lib": ["dom", "dom.iterable", "esnext"],
            "allowJs": True,
            "skipLibCheck": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "module": "esnext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "isolatedModules": True,
            "jsx": "react-jsx",
            "incremental": True,
            "plugins": [{"name": "next"}],
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        "exclude": ["node_modules"],
    }
    return json.dumps(config, indent=2) + "\n"


def _layout_tsx(config: PaperSiteConfig) -> str:
    return f'''import type {{ Metadata }} from "next";
import type {{ ReactNode }} from "react";
import {{ GeistSans }} from "geist/font/sans";
import {{ GeistMono }} from "geist/font/mono";
import "./globals.css";

export const metadata: Metadata = {{
  title: "{_escape_ts(config.title)}",
  description: "Native PaperScope paper reader",
}};

export default function RootLayout({{ children }}: {{ children: ReactNode }}) {{
  return (
    <html lang="en" suppressHydrationWarning className={{`${{GeistSans.variable}} ${{GeistMono.variable}}`}}>
      <head>
        <script
          dangerouslySetInnerHTML={{{{
            __html: `try{{var t=localStorage.getItem('theme');if(t==='dark'||(!t&&matchMedia('(prefers-color-scheme: dark)').matches))document.documentElement.classList.add('dark');}}catch(e){{}}`,
          }}}}
        />
      </head>
      <body>{{children}}</body>
    </html>
  );
}}
'''


def _page_tsx() -> str:
    return '''import fs from "node:fs";
import path from "node:path";
import PaperReader, { type DetailHighlight, type PaperSection, type Reference } from "./PaperReader";

type SectionRecord = {
  id: string;
  label: string;
  eyebrow?: string;
  manuscript?: string;
  manuscriptPath?: string;
  manuscript_path?: string;
};

function readSections(): PaperSection[] | undefined {
  const sectionsPath = path.join(process.cwd(), "src/content/sections.json");
  if (!fs.existsSync(sectionsPath)) return undefined;

  const records = JSON.parse(fs.readFileSync(sectionsPath, "utf8")) as SectionRecord[];
  return records.map((record) => {
    const manuscript =
      record.manuscript ??
      fs.readFileSync(
        path.join(process.cwd(), record.manuscriptPath ?? record.manuscript_path ?? `src/content/${record.id}.md`),
        "utf8"
      );
    return { id: record.id, label: record.label, eyebrow: record.eyebrow, manuscript };
  });
}

function readContent() {
  const manuscript = fs.readFileSync(path.join(process.cwd(), "src/content/manuscript.md"), "utf8");
  const references = JSON.parse(fs.readFileSync(path.join(process.cwd(), "src/content/references.json"), "utf8")) as Reference[];
  const details = JSON.parse(fs.readFileSync(path.join(process.cwd(), "src/content/details.json"), "utf8")) as DetailHighlight[];
  const sections = readSections();
  return { manuscript, references, details, sections };
}

export default function Page() {
  const { manuscript, references, details, sections } = readContent();
  return <PaperReader manuscript={manuscript} references={references} details={details} sections={sections} />;
}
'''


def _paper_reader_tsx() -> str:
    return '''"use client";

import { Children, Fragment, cloneElement, isValidElement, useEffect, useMemo, useRef, useState, type ReactElement, type ReactNode } from "react";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";

export type Reference = {
  key: string;
  label: string;
  full: string;
  title?: string;
  authors?: string;
  year?: string;
  doi?: string;
  native_href?: string;
  source_href?: string;
  role?: string;
  what?: string;
  why?: string;
  caution?: string;
  contexts?: Array<string | { context?: string; text?: string; line?: number }>;
  paperlibrary_status?: string;
  paperlibrary_note?: string;
};

export type DetailHighlight = {
  id: string;
  phrase: string;
  title: string;
  summary: string;
  bullets?: string[];
};

export type PaperSection = {
  id: string;
  label: string;
  manuscript: string;
  eyebrow?: string;
};

type ScrollSnapshot = { windowTop: number; articleTop: number };

const topScroll: ScrollSnapshot = { windowTop: 0, articleTop: 0 };

function normalizePaperSections(manuscript: string, sections?: PaperSection[]): PaperSection[] {
  const cleaned = (sections ?? []).filter((section) => section.id && section.label && section.manuscript);
  if (cleaned.length > 0) return cleaned;

  return [{ id: "manuscript", label: "Manuscript", eyebrow: "Native manuscript", manuscript }];
}

type Active = { kind: "ref"; id: string } | { kind: "detail"; id: string } | null;

type Context = {
  refs: Map<string, Reference>;
  details: DetailHighlight[];
  active: Active;
  onOpen: (next: Active) => void;
};

const CITE_RE = /\\[@[A-Za-z0-9_:-]+(?:\\s*;\\s*@[A-Za-z0-9_:-]+)*\\]/;

function citationKeys(group: string): string[] {
  return group
    .slice(1, -1)
    .split(";")
    .map((key) => key.trim().replace(/^@/, ""))
    .filter(Boolean);
}

function pushTextNode(out: ReactNode[], value: string, key: string) {
  if (value) out.push(<Fragment key={key}>{value}</Fragment>);
}

function nextDetailMatch(text: string, details: DetailHighlight[]): { detail: DetailHighlight; index: number } | null {
  let best: { detail: DetailHighlight; index: number } | null = null;
  for (const detail of details) {
    const index = text.indexOf(detail.phrase);
    if (index === -1) continue;
    if (!best || index < best.index || (index === best.index && detail.phrase.length > best.detail.phrase.length)) {
      best = { detail, index };
    }
  }
  return best;
}

function withInteractions(children: ReactNode, ctx: Context, key = "k"): ReactNode {
  return Children.map(children, (child, index) => {
    if (typeof child === "string") return splitInteractiveText(child, ctx, `${key}-${index}`);
    if (isValidElement(child)) {
      const element = child as ReactElement<{ children?: ReactNode }>;
      if (element.props.children != null) {
        return cloneElement(element, { key: `${key}-${index}` }, withInteractions(element.props.children, ctx, `${key}-${index}`));
      }
    }
    return child;
  });
}

function splitInteractiveText(text: string, ctx: Context, key: string): ReactNode[] {
  const out: ReactNode[] = [];
  let rest = text;
  let guard = 0;

  while (rest.length && guard < 800) {
    const citation = rest.match(CITE_RE);
    const citationIndex = citation?.index;
    const detail = nextDetailMatch(rest, ctx.details);

    if ((citationIndex === undefined || citationIndex === -1) && !detail) {
      pushTextNode(out, rest, `${key}-text-${guard}`);
      break;
    }

    if (detail && (citationIndex === undefined || detail.index < citationIndex)) {
      if (detail.index > 0) pushTextNode(out, rest.slice(0, detail.index), `${key}-text-${guard}-pre`);
      const active = ctx.active?.kind === "detail" && ctx.active.id === detail.detail.id;
      out.push(
        <span
          role="button"
          tabIndex={0}
          className={`detail-highlight${active ? " active" : ""}`}
          onClick={() => ctx.onOpen({ kind: "detail", id: detail.detail.id })}
          onKeyDown={(event) => {
            if (event.key === "Enter" || event.key === " ") {
              event.preventDefault();
              ctx.onOpen({ kind: "detail", id: detail.detail.id });
            }
          }}
          key={`${key}-detail-${guard}`}
        >
          {detail.detail.phrase}
        </span>
      );
      rest = rest.slice(detail.index + detail.detail.phrase.length);
      guard += 1;
      continue;
    }

    if (!citation || citationIndex === undefined) {
      pushTextNode(out, rest, `${key}-text-${guard}`);
      break;
    }

    if (citationIndex > 0) pushTextNode(out, rest.slice(0, citationIndex), `${key}-text-${guard}-pre`);
    out.push(<CitationGroup key={`${key}-cite-${guard}`} keys={citationKeys(citation[0])} ctx={ctx} id={`${key}-cite-${guard}`} />);
    rest = rest.slice(citationIndex + citation[0].length);
    guard += 1;
  }
  return out;
}

function CitationGroup({ keys, ctx, id }: { keys: string[]; ctx: Context; id: string }) {
  return (
    <span className="cite" id={id}>
      {"("}
      {keys.map((key, index) => {
        return (
          <Fragment key={`${id}-${key}-${index}`}>
            <ReferenceInlineLink refKey={key} ctx={ctx} />
            {index < keys.length - 1 ? "; " : ""}
          </Fragment>
        );
      })}
      {")"}
    </span>
  );
}

function ReferenceInlineLink({ refKey, ctx }: { refKey: string; ctx: Context }) {
  const ref = ctx.refs.get(refKey);
  const active = ctx.active?.kind === "ref" && ctx.active.id === refKey;
  if (!ref) return <span className="cite-link">{refKey}</span>;
  return (
    <button type="button" className={`cite-link${active ? " active" : ""}`} onClick={() => ctx.onOpen({ kind: "ref", id: refKey })}>
      {ref.label}
    </button>
  );
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&");
}

type ReferenceMention = { refKey: string; index: number; end: number; length: number };

function referenceMentionSurfaces(refs: Map<string, Reference>): Array<{ refKey: string; surface: string }> {
  const surfaces: Array<{ refKey: string; surface: string }> = [];
  const seen = new Set<string>();
  for (const [refKey, reference] of refs) {
    for (const surface of [refKey, reference.label]) {
      const normalized = surface.trim();
      const dedupeKey = normalized.toLowerCase();
      if (normalized.length < 4 || seen.has(dedupeKey)) continue;
      seen.add(dedupeKey);
      surfaces.push({ refKey, surface: normalized });
    }
  }
  return surfaces.sort((a, b) => b.surface.length - a.surface.length);
}

function nextReferenceMention(text: string, refs: Map<string, Reference>): ReferenceMention | null {
  let best: ReferenceMention | null = null;
  for (const candidate of referenceMentionSurfaces(refs)) {
    const pattern = new RegExp(`(^|[^A-Za-z0-9_:-])(${escapeRegExp(candidate.surface)})(?=$|[^A-Za-z0-9_:-])`, "i");
    const match = text.match(pattern);
    if (!match || match.index === undefined) continue;
    const prefixLength = match[1]?.length ?? 0;
    const matchedText = match[2];
    const index = match.index + prefixLength;
    const mention = { refKey: candidate.refKey, index, end: index + matchedText.length, length: matchedText.length };
    if (!best || mention.index < best.index || (mention.index === best.index && mention.length > best.length)) {
      best = mention;
    }
  }
  return best;
}

function splitSidebarText(text: string, ctx: Context, key: string): ReactNode[] {
  const out: ReactNode[] = [];
  let rest = text;
  let guard = 0;

  while (rest.length && guard < 800) {
    const citation = rest.match(CITE_RE);
    const citationIndex = citation?.index;
    const refMention = nextReferenceMention(rest, ctx.refs);

    if ((citationIndex === undefined || citationIndex === -1) && !refMention) {
      pushTextNode(out, rest, `${key}-text-${guard}`);
      break;
    }

    if (refMention && (citationIndex === undefined || refMention.index < citationIndex)) {
      if (refMention.index > 0) pushTextNode(out, rest.slice(0, refMention.index), `${key}-text-${guard}-pre`);
      out.push(<ReferenceInlineLink refKey={refMention.refKey} ctx={ctx} key={`${key}-ref-mention-${guard}`} />);
      rest = rest.slice(refMention.end);
      guard += 1;
      continue;
    }

    if (!citation || citationIndex === undefined) {
      pushTextNode(out, rest, `${key}-text-${guard}`);
      break;
    }

    if (citationIndex > 0) pushTextNode(out, rest.slice(0, citationIndex), `${key}-text-${guard}-pre`);
    out.push(<CitationGroup key={`${key}-cite-${guard}`} keys={citationKeys(citation[0])} ctx={ctx} id={`${key}-cite-${guard}`} />);
    rest = rest.slice(citationIndex + citation[0].length);
    guard += 1;
  }
  return out;
}

function linkSidebarReferences(children: ReactNode, ctx: Context, key = "sidebar"): ReactNode {
  return Children.map(children, (child, index) => {
    if (typeof child === "string") return splitSidebarText(child, ctx, `${key}-${index}`);
    if (isValidElement(child)) {
      const element = child as ReactElement<{ children?: ReactNode }>;
      if (element.props.children != null) {
        return cloneElement(element, { key: `${key}-${index}` }, linkSidebarReferences(element.props.children, ctx, `${key}-${index}`));
      }
    }
    return child;
  });
}

type ReferenceUseNote = {
  role: string;
  what: string;
  why: string;
  caution: string;
};

function referenceSearchText(ref: Reference): string {
  return [ref.title, ref.full, ref.contexts?.map((context) => (typeof context === "string" ? context : context.context ?? context.text ?? "")).join(" ")]
    .filter(Boolean)
    .join(" ")
    .toLowerCase();
}

function referenceUseNote(ref: Reference): ReferenceUseNote {
  if (ref.role && ref.what && ref.why && ref.caution) {
    return { role: ref.role, what: ref.what, why: ref.why, caution: ref.caution };
  }

  const text = referenceSearchText(ref);
  if (/guideline|recommendation|consensus|practice guideline|protocol|position statement/.test(text)) {
    return {
      role: ref.role ?? "Clinical guidance",
      what: ref.what ?? `${ref.label} is used as a guidance source for the local recommendation or clinical workflow being discussed.`,
      why:
        ref.why ??
        "The generated page should make clear whether the source is carrying a recommendation, a safety constraint, a diagnostic threshold, or a workflow step.",
      caution:
        ref.caution ??
        "Guidelines are context-sensitive. Check jurisdiction, population, date, and whether the page is quoting a recommendation directly or applying it locally.",
    };
  }

  if (/systematic review|meta-analysis|review/.test(text)) {
    return {
      role: ref.role ?? "Evidence synthesis",
      what: ref.what ?? `${ref.label} is used to summarise a broader evidence base rather than stand in for a single primary result.`,
      why:
        ref.why ??
        "The sidebar should help readers see which part of the synthesis matters: effect direction, uncertainty, heterogeneity, subgroup limits, or background framing.",
      caution:
        ref.caution ??
        "A review inherits the limits of its included studies. Treat it as synthesis, not as automatic proof that every setting or subgroup is covered.",
    };
  }

  if (/randomi[sz]ed|trial|cohort|case-control|registry|observational/.test(text)) {
    return {
      role: ref.role ?? "Primary empirical evidence",
      what: ref.what ?? `${ref.label} supplies primary data for one step in the argument.`,
      why:
        ref.why ??
        "The reader should be able to tell whether this source is supporting an estimate, a mechanism, a comparator, a safety issue, or a boundary condition.",
      caution:
        ref.caution ??
        "Primary studies need population, intervention/exposure, comparator, outcome, and bias limits kept visible before their result is generalised.",
    };
  }

  if (/bayes|predictive|inference|model|algorithm|dynamics|control|manifold|neural|cortex/.test(text)) {
    return {
      role: ref.role ?? "Conceptual or modelling support",
      what: ref.what ?? `${ref.label} supplies a model, framework, or comparison point for the local claim.`,
      why:
        ref.why ??
        "The useful question is what explanatory work the source is doing here: defining a framework, motivating a comparison, or constraining a mechanism.",
      caution:
        ref.caution ??
        "A framework citation does not automatically settle implementation. Read it against the exact manuscript context rather than as global endorsement.",
    };
  }

  return {
    role: ref.role ?? "Supporting source",
    what: ref.what ?? `${ref.label} supplies background, precedent, or a comparison point for the local claim.`,
    why:
      ref.why ??
      "The sidebar should explain the source's local job so readers are not left with a bibliography entry and no interpretive guidance.",
    caution:
      ref.caution ??
      "Read the cited passage alongside the context below; the source is being used for that local role rather than to outsource the whole conclusion.",
  };
}

function citationText(keys: string, parenthetical: boolean): string {
  const citeKeys = keys
    .split(",")
    .map((key) => key.trim())
    .filter(Boolean);
  return parenthetical ? `[${citeKeys.map((key) => `@${key}`).join("; ")}]` : citeKeys.join(", ");
}

function cleanCitationContext(context: string): string {
  return context
    .replace(/\\\\citet(?:\\[[^\\]]*\\]){0,2}\\{([^}]+)\\}/g, (_, keys: string) => citationText(keys, false))
    .replace(/\\\\citep(?:\\[[^\\]]*\\]){0,2}\\{([^}]+)\\}/g, (_, keys: string) => citationText(keys, true))
    .replace(/\\\\cite(?:\\[[^\\]]*\\]){0,2}\\{([^}]+)\\}/g, (_, keys: string) => citationText(keys, true))
    .replace(/\\\\emph\\{([^}]+)\\}/g, "$1")
    .replace(/``|''/g, '"')
    .replace(/~/g, " ")
    .replace(/\\\\&/g, "&");
}

function referenceContexts(ref: Reference): string[] {
  const seen = new Set<string>();
  const contexts: string[] = [];
  for (const raw of ref.contexts ?? []) {
    const text = typeof raw === "string" ? raw : raw.context ?? raw.text ?? "";
    const cleaned = cleanCitationContext(text);
    const key = cleaned.toLowerCase();
    if (!cleaned || seen.has(key)) continue;
    seen.add(key);
    contexts.push(cleaned);
  }
  return contexts;
}

function paperLibraryStatusText(ref: Reference): string {
  if (ref.paperlibrary_status === "have_text") {
    return "The paper library (~/paper-library) has harvested text for this source, so the citation can be checked against local source material rather than metadata alone.";
  }
  if (ref.paperlibrary_status) {
    return `Paper-library status: ${ref.paperlibrary_status}. The source remains visible so the citation role can still be inspected.`;
  }
  return "Paper-library status is not recorded for this source. The citation role is shown from the generated site inventory.";
}

function DetailLayer({ label, children, ctx }: { label: string; children: ReactNode; ctx: Context }) {
  return (
    <div className="paper-layer">
      <p className="md-eyebrow">{label}</p>
      <div>{linkSidebarReferences(children, ctx)}</div>
    </div>
  );
}

function ReferenceUsePanel({ ref, ctx }: { ref: Reference; ctx: Context }) {
  const note = referenceUseNote(ref);
  const contexts = referenceContexts(ref);
  return (
    <>
      <section className="reference-explainer">
        <p className="reference-role">{note.role}</p>
        <p>{linkSidebarReferences(note.what, ctx)}</p>
      </section>
      <DetailLayer label="Why it matters here" ctx={ctx}>
        <p>{note.why}</p>
      </DetailLayer>
      <DetailLayer label="How to read the citation" ctx={ctx}>
        <p>{note.caution}</p>
      </DetailLayer>
      {contexts.length ? (
        <DetailLayer label="Where it appears" ctx={ctx}>
          <ol className="context-list compact">
            {contexts.slice(0, 3).map((context, index) => (
              <li key={`${ref.key}-context-${index}`}>{context}</li>
            ))}
          </ol>
        </DetailLayer>
      ) : null}
    </>
  );
}

export default function PaperReader({
  manuscript,
  references,
  details,
  sections,
}: {
  manuscript: string;
  references: Reference[];
  details: DetailHighlight[];
  sections?: PaperSection[];
}) {
  const paperSections = useMemo(() => normalizePaperSections(manuscript, sections), [manuscript, sections]);
  const [activeSectionId, setActiveSectionId] = useState(() => paperSections[0]?.id ?? "manuscript");
  const [active, setActive] = useState<Active>(null);
  const paperMainRef = useRef<HTMLElement>(null);
  const activeSectionRef = useRef(activeSectionId);
  const savedScrollBySection = useRef<Record<string, ScrollSnapshot>>({});
  const pendingScroll = useRef<ScrollSnapshot | null>(null);
  const refs = useMemo(() => new Map(references.map((ref) => [ref.key, ref])), [references]);
  const activeSection = paperSections.find((section) => section.id === activeSectionId) ?? paperSections[0];
  const activeRef = active?.kind === "ref" ? refs.get(active.id) ?? null : null;
  const activeDetail = active?.kind === "detail" ? details.find((detail) => detail.id === active.id) ?? null : null;
  const ctx = { refs, details, active, onOpen: setActive };

  function readScrollSnapshot(): ScrollSnapshot {
    return {
      windowTop: window.scrollY,
      articleTop: paperMainRef.current?.scrollTop ?? 0,
    };
  }

  function restoreScrollSnapshot(snapshot: ScrollSnapshot) {
    window.scrollTo({ top: snapshot.windowTop, behavior: "auto" });
    paperMainRef.current?.scrollTo({ top: snapshot.articleTop, behavior: "auto" });
  }

  function switchSection(nextSectionId: string) {
    const currentSectionId = activeSectionRef.current;
    if (nextSectionId === currentSectionId) return;

    savedScrollBySection.current[currentSectionId] = readScrollSnapshot();
    pendingScroll.current = savedScrollBySection.current[nextSectionId] ?? topScroll;
    setActiveSectionId(nextSectionId);
  }

  useEffect(() => {
    if (paperSections.some((section) => section.id === activeSectionId)) return;
    setActiveSectionId(paperSections[0]?.id ?? "manuscript");
  }, [activeSectionId, paperSections]);

  useEffect(() => {
    activeSectionRef.current = activeSectionId;
    if (pendingScroll.current === null) return;

    const snapshot = pendingScroll.current;
    pendingScroll.current = null;
    window.requestAnimationFrame(() => {
      restoreScrollSnapshot(snapshot);
    });
  }, [activeSectionId]);

  const components: Components = {
    p: ({ children }) => <p>{withInteractions(children, ctx)}</p>,
    li: ({ children }) => <li>{withInteractions(children, ctx)}</li>,
    a: ({ children, href }) => (
      <a href={href} target="_blank" rel="noreferrer">
        {withInteractions(children, ctx)}
      </a>
    ),
  };

  return (
    <main className="paper-split">
      <section className="paper-main" ref={paperMainRef}>
        <div className="paper-main-inner">
          {paperSections.length > 1 ? (
            <div className="paper-section-tabs" role="tablist" aria-label="Paper sections">
              {paperSections.map((section) => {
                const selected = section.id === activeSection.id;
                return (
                  <button
                    key={section.id}
                    type="button"
                    className={`paper-section-tab${selected ? " active" : ""}`}
                    aria-selected={selected}
                    role="tab"
                    onClick={() => switchSection(section.id)}
                  >
                    {section.label}
                  </button>
                );
              })}
            </div>
          ) : null}
          <p className="md-eyebrow">{activeSection.eyebrow ?? "Native manuscript"}</p>
          <article className="paper" key={activeSection.id}>
            <ReactMarkdown remarkPlugins={[remarkGfm]} components={components}>
              {activeSection.manuscript}
            </ReactMarkdown>
          </article>
        </div>
      </section>
      <aside className={`paper-aside${activeRef || activeDetail ? " open" : ""}`}>
        {activeRef ? (
          <>
            <div className="paper-panel-head">
              <p className="md-eyebrow">Reference</p>
              <button type="button" className="md-btn md-btn-text" onClick={() => setActive(null)} aria-label="Close reference panel">
                x
              </button>
            </div>
            <h2>{activeRef.label}</h2>
            <p className="reference-full">{linkSidebarReferences(activeRef.full, ctx)}</p>
            <div className="paper-panel-actions">
              {activeRef.native_href ? (
                <a className="md-btn md-btn-tonal" href={activeRef.native_href} target="_blank" rel="noreferrer">
                  Native page
                </a>
              ) : null}
              {activeRef.source_href ? (
                <a className="md-btn md-btn-tonal" href={activeRef.source_href} target="_blank" rel="noreferrer">
                  Source
                </a>
              ) : null}
              {activeRef.doi ? (
                <a className="md-btn md-btn-tonal" href={`https://doi.org/${activeRef.doi}`} target="_blank" rel="noreferrer">
                  DOI
                </a>
              ) : null}
            </div>
            <ReferenceUsePanel ref={activeRef} ctx={ctx} />
            <DetailLayer label="Paper library" ctx={ctx}>
              <p>{paperLibraryStatusText(activeRef)}</p>
              {activeRef.paperlibrary_note ? <p>{activeRef.paperlibrary_note}</p> : null}
            </DetailLayer>
          </>
        ) : activeDetail ? (
          <>
            <div className="paper-panel-head">
              <p className="md-eyebrow">More detail</p>
              <button type="button" className="md-btn md-btn-text" onClick={() => setActive(null)} aria-label="Close detail panel">
                x
              </button>
            </div>
            <h2>{activeDetail.title}</h2>
            <p className="reference-full">{linkSidebarReferences(activeDetail.summary, ctx)}</p>
            {activeDetail.bullets?.length ? (
              <ul className="detail-list">
                {activeDetail.bullets.map((bullet, index) => (
                  <li key={`${activeDetail.id}-bullet-${index}`}>{linkSidebarReferences(bullet, ctx)}</li>
                ))}
              </ul>
            ) : null}
          </>
        ) : (
          <>
            <p className="md-eyebrow">Reference layer</p>
            <h2>Paper-library coverage</h2>
            <div className="paper-panel-stats">
              <div>
                <strong>{references.length}</strong>
                <span>references</span>
              </div>
              <div>
                <strong>{references.filter((ref) => ref.paperlibrary_status === "have_text").length}</strong>
                <span>held texts</span>
              </div>
            </div>
            <ol className="reference-bibliography">
              {references.map((ref) => (
                <li key={ref.key}>
                  <p>{ref.full}</p>
                  <div className="reference-bibliography-links">
                    {ref.doi ? <a href={`https://doi.org/${ref.doi}`}>DOI</a> : null}
                  </div>
                </li>
              ))}
            </ol>
          </>
        )}
      </aside>
    </main>
  );
}
'''


def _sample_manuscript(config: PaperSiteConfig) -> str:
    return f"""# {config.title}

This native paper page is generated from the shared PaperScope reader scaffold.

Inline references should open the reader panel before sending readers to an
external DOI or source page. More-detail annotations should read like subtle
scholarly marks in the sentence, not like block callouts.

This scaffold includes an example citation [@example2026] and a generated inline
detail marker.
"""


def _sample_references() -> str:
    return json.dumps(
        [
            {
                "key": "example2026",
                "label": "Example 2026",
                "title": "Example paper",
                "full": "Example Author. Example paper. Example Journal, 2026.",
                "doi": "10.0000/example",
                "role": "Example source role",
                "what": "Example 2026 is used to demonstrate the generated reference-use sidebar contract.",
                "why": "Generated sites should explain what each citation is doing rather than showing only a bibliographic record.",
                "caution": "Replace this sample note with source-specific prose before using the page as a durable public artifact.",
                "contexts": [
                    "This scaffold includes an example citation [@example2026] and a generated inline detail marker."
                ],
                "paperlibrary_status": "have_text",
            }
        ],
        indent=2,
    ) + "\n"


def _sample_details() -> str:
    return json.dumps(
        [
            {
                "id": "generated-inline-detail",
                "phrase": "generated inline detail marker",
                "title": "Inline detail marker",
                "summary": "Detail markers open the side panel while preserving the article's reading rhythm.",
                "bullets": [
                    "They should be visually closer to a scholarly annotation than a callout; see [@example2026].",
                    "The same component is used by academic and medical paper sites.",
                ],
            }
        ],
        indent=2,
    ) + "\n"


def _escape_ts(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


SHARED_CSS = """:root {
  --md-primary: #1c5888;
  --md-on-primary: #ffffff;
  --md-primary-container: #d9ecff;
  --md-on-primary-container: #1c507b;
  --md-secondary: #2c7191;
  --md-on-secondary: #ffffff;
  --md-secondary-container: #d1efff;
  --md-on-secondary-container: #025473;
  --md-tertiary: #b0552f;
  --md-on-tertiary: #ffffff;
  --md-tertiary-container: #ffe3d8;
  --md-on-tertiary-container: #773c24;
  --md-app-background: linear-gradient(180deg, #f8fbfc 0%, #f4f7f7 44%, #fafafa 100%);
  --md-surface: #f8fafb;
  --md-surface-bright: #ffffff;
  --md-surface-container-lowest: #ffffff;
  --md-surface-container-low: #f2f6f7;
  --md-surface-container: #eaf0f2;
  --md-surface-container-high: #e1eaed;
  --md-surface-container-highest: #d7e2e6;
  --md-on-surface: #171d22;
  --md-on-surface-variant: #4d5860;
  --md-outline: #73777f;
  --md-outline-variant: #c3c6cf;
  --md-outline-soft: color-mix(in srgb, var(--md-outline-variant) 68%, transparent);
  --md-shadow-1: 0 1px 2px rgba(21, 35, 46, 0.06), 0 8px 24px rgba(21, 35, 46, 0.06);
  --md-shadow-2: 0 2px 4px rgba(21, 35, 46, 0.08), 0 14px 34px rgba(21, 35, 46, 0.09);
  --md-shadow-3: 0 8px 18px rgba(21, 35, 46, 0.12), 0 24px 56px rgba(21, 35, 46, 0.12);
  --md-radius-xs: 4px;
  --md-radius-sm: 8px;
  --md-radius-md: 12px;
  --md-radius-lg: 16px;
  --md-radius-xl: 28px;
  --md-radius-full: 9999px;
  --header-h: 56px;
}

.dark {
  --md-primary: #6e9fcc;
  --md-on-primary: #00213b;
  --md-primary-container: #1a4b73;
  --md-on-primary-container: #d0e8ff;
  --md-secondary: #68a2c0;
  --md-on-secondary: #002332;
  --md-secondary-container: #0f4e69;
  --md-on-secondary-container: #c6ebff;
  --md-tertiary: #d2886b;
  --md-on-tertiary: #3a1000;
  --md-tertiary-container: #733216;
  --md-on-tertiary-container: #ffdccf;
  --md-app-background: linear-gradient(180deg, #11161a 0%, #0f1215 48%, #121212 100%);
  --md-surface: #12161a;
  --md-surface-bright: #1e1e1e;
  --md-surface-container-lowest: #0a0a0a;
  --md-surface-container-low: #171d21;
  --md-surface-container: #1d252a;
  --md-surface-container-high: #273137;
  --md-surface-container-highest: #313d44;
  --md-on-surface: #e3e3e3;
  --md-on-surface-variant: #c3c6cf;
  --md-outline: #8d9199;
  --md-outline-variant: #43474e;
  --md-outline-soft: color-mix(in srgb, var(--md-outline-variant) 62%, transparent);
}

* {
  box-sizing: border-box;
}

html {
  color-scheme: light dark;
}

body {
  margin: 0;
  min-height: 100vh;
  background: var(--md-app-background);
  background-attachment: fixed;
  color: var(--md-on-surface);
  font-family: var(--font-geist-sans), system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

a {
  color: var(--md-primary);
}

.md-eyebrow {
  color: var(--md-on-surface-variant);
  font-size: 0.72rem;
  font-weight: 600;
  letter-spacing: 0.09em;
  text-transform: uppercase;
}

.md-btn {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  gap: 0.5rem;
  border: 1px solid transparent;
  border-radius: var(--md-radius-full);
  cursor: pointer;
  font: inherit;
  font-size: 0.92rem;
  font-weight: 550;
  line-height: 1;
  padding: 0.7rem 1.15rem;
  text-decoration: none;
  transition: filter 130ms ease, box-shadow 130ms ease, background 130ms ease;
}

.md-btn-tonal {
  background: var(--md-primary-container);
  color: var(--md-on-primary-container);
}

.md-btn-text {
  background: transparent;
  color: var(--md-primary);
  padding: 0.5rem 0.6rem;
}

.paper-split {
  display: flex;
  align-items: stretch;
  min-height: 100vh;
}

.paper-main {
  flex: 1 1 auto;
  min-width: 0;
  overflow-y: auto;
  padding: 1.75rem clamp(1rem, 4vw, 3rem) 4rem;
}

.paper-main-inner {
  width: min(100%, 760px);
  margin: 0 auto;
}

.paper-section-tabs {
  display: flex;
  align-items: center;
  gap: 0.4rem;
  margin: 0 0 1rem;
  padding: 0 0 0.75rem;
  overflow-x: auto;
  border-bottom: 1px solid var(--md-outline-variant);
}

.paper-section-tab {
  appearance: none;
  border: 1px solid transparent;
  border-radius: var(--md-radius-full);
  background: transparent;
  color: var(--md-on-surface-variant);
  cursor: pointer;
  flex: 0 0 auto;
  font: inherit;
  font-size: 0.88rem;
  font-weight: 650;
  line-height: 1;
  padding: 0.55rem 0.85rem;
}

.paper-section-tab:hover {
  background: color-mix(in srgb, var(--md-primary) 8%, transparent);
}

.paper-section-tab.active {
  color: var(--md-on-primary-container);
  background: var(--md-primary-container);
  border-color: color-mix(in srgb, var(--md-primary) 40%, var(--md-outline-variant));
}

.paper-section-tab:focus-visible {
  outline: 2px solid var(--md-primary);
  outline-offset: 2px;
}

.paper {
  font-family: "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, "Times New Roman", serif;
  font-size: 1.05rem;
  line-height: 1.72;
}

.paper h1,
.paper h2,
.paper h3,
.paper h4 {
  font-family: var(--font-geist-sans), system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  letter-spacing: 0;
}

.paper h2 {
  margin: 2.4rem 0 0.6rem;
  padding-top: 0.4rem;
  border-top: 1px solid var(--md-outline-variant);
  font-size: 1.18rem;
}

.cite-link {
  border-radius: 2px;
}

.cite-link {
  appearance: none;
  border: 0;
  background: transparent;
  color: var(--md-primary);
  cursor: pointer;
  font: inherit;
  padding: 0;
  text-decoration: underline;
  text-decoration-style: dotted;
  text-decoration-color: color-mix(in srgb, var(--md-primary) 55%, transparent);
  text-underline-offset: 0.18em;
}

.cite-link:hover,
.cite-link.active {
  color: var(--md-on-primary-container);
  text-decoration-color: var(--md-primary);
}

.cite-link.active {
  text-decoration-thickness: 2px;
}


.detail-highlight {
  display: inline;
  background:
    linear-gradient(
      to top,
      color-mix(in srgb, var(--md-tertiary-container) 58%, transparent) 0 42%,
      transparent 42% 100%
    );
  -webkit-box-decoration-break: clone;
  box-decoration-break: clone;
  color: inherit;
  cursor: pointer;
  text-decoration: none;
}

.detail-highlight:hover,
.detail-highlight.active {
  background:
    linear-gradient(
      to top,
      color-mix(in srgb, var(--md-tertiary-container) 86%, transparent) 0 58%,
      transparent 58% 100%
    );
}

.paper-aside {
  flex: 0 0 clamp(360px, 35%, 480px);
  overflow-y: auto;
  border-left: 1px solid var(--md-outline-variant);
  background: color-mix(in srgb, var(--md-surface-container-low) 88%, var(--md-primary-container) 12%);
  padding: 1.5rem 1.5rem 3rem;
}

.paper-aside h2 {
  margin: 0.45rem 0 0;
  font-size: 1.12rem;
  line-height: 1.3;
}

.paper-panel-head {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 1rem;
}

.paper-panel-head .md-btn {
  min-height: 1.8rem;
  padding: 0.1rem 0.45rem;
  font-size: 1rem;
}

.paper-panel-actions {
  display: flex;
  flex-wrap: wrap;
  gap: 0.7rem;
  margin-top: 1rem;
}

.reference-full {
  margin: 0.65rem 0 0;
  color: var(--md-on-surface-variant);
  font-size: 0.95rem;
  line-height: 1.55;
}

.reference-explainer {
  margin-top: 1rem;
  border: 1px solid color-mix(in srgb, var(--md-primary) 24%, var(--md-outline-variant));
  border-radius: var(--md-radius-sm);
  background: color-mix(in srgb, var(--md-primary-container) 28%, var(--md-surface-container-lowest));
  padding: 0.9rem;
}

.reference-explainer p {
  margin: 0.55rem 0 0;
  color: var(--md-on-surface);
  font-size: 0.93rem;
  line-height: 1.55;
}

.reference-explainer .reference-role {
  display: inline-flex;
  width: fit-content;
  margin: 0;
  border-radius: var(--md-radius-full);
  background: var(--md-surface-container-lowest);
  color: var(--md-primary);
  font-size: 0.72rem;
  font-weight: 650;
  letter-spacing: 0.04em;
  padding: 0.24rem 0.55rem;
  text-transform: uppercase;
}

.paper-layer {
  margin-top: 1.2rem;
  padding-top: 1rem;
  border-top: 1px solid var(--md-outline-variant);
}

.paper-layer p {
  color: var(--md-on-surface-variant);
  font-size: 0.92rem;
  line-height: 1.58;
}

.detail-list {
  margin: 1rem 0 0;
  padding-left: 1.1rem;
  color: var(--md-on-surface-variant);
  line-height: 1.58;
}

.context-list {
  display: grid;
  gap: 0.65rem;
  margin: 0;
  padding-left: 1.2rem;
}

.context-list li {
  color: var(--md-on-surface-variant);
  font-size: 0.9rem;
  line-height: 1.5;
}

.context-list.compact {
  gap: 0.45rem;
}

.context-list.compact li {
  font-size: 0.86rem;
}

.paper-panel-stats {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 0.75rem;
}

.paper-panel-stats div,
.reference-bibliography li {
  border: 1px solid var(--md-outline-variant);
  border-radius: var(--md-radius-md);
  background: var(--md-surface-container-lowest);
  padding: 0.85rem;
}

.paper-panel-stats strong,
.paper-panel-stats span {
  display: block;
}

.paper-panel-stats span,
.reference-bibliography p {
  color: var(--md-on-surface-variant);
}

.reference-bibliography {
  display: grid;
  gap: 0.75rem;
  padding: 0;
  list-style: none;
}

.reference-bibliography-links {
  display: flex;
  gap: 0.7rem;
}
"""
